name: Alloverse Documentation Site Deployment

on:
  schedule: 
    - cron: '0 6 * * 1'
  push:
    branches:
      - main

jobs: 
  github-pages:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: git submodule update --init --remote
      - run: sudo apt-get install -y luarocks
      - run: sudo luarocks install ldoc
      - run: ldoc -l _generation -x .md -f markdown _generation/libs
      - uses: helaili/jekyll-action@2.0.5
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
